config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tasks do
    resources :sub_tasks 
  end

  resources :users, only: [:index, :show]

  root 'pages#home'

end

app/models/sub_task.rb
class SubTask < ActiveRecord::Base
  default_scope { order('sort_order DESC') }
  
  validates_presence_of :body, :task_id

  belongs_to :task, counter_cache: true, touch: true

  before_create :set_sort_order
  
  def set_sort_order
    last_sub_task = task.sub_tasks.first
    self.sort_order = last_sub_task ? last_sub_task.sort_order + 1 : 1
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  default_scope { order('sort_order DESC') } 

  scope :with_sub_tasks, -> { includes(:sub_tasks)}
  scope :public_tasks, -> { where(public: true)}

  belongs_to :user, counter_cache: true

  has_many :sub_tasks, dependent: :destroy
  accepts_nested_attributes_for :sub_tasks, allow_destroy: true
  
  validates_presence_of :body

  before_create :set_sort_order

  def set_sort_order
    last_task = user.tasks.first
    self.sort_order = last_task ? last_task.sort_order + 1 : 1
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  scope :with_public_tasks, -> { includes(:tasks).includes(tasks: :sub_tasks).where(tasks: {public: true})}

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  has_many :tasks, dependent: :destroy
  has_many :sub_tasks, through: :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  after_filter :set_csrf_cookie_for_ng
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end


  def set_csrf_cookie_for_ng
    cookies['XSRF-TOKEN'] = form_authenticity_token if protect_against_forgery?
  end

  protected

  def verified_request?
    super || form_authenticity_token == request.headers['X-XSRF-TOKEN']
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    
  end

end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController

  before_action :authenticate_user!

  before_action :set_sub_task, only: [:update, :destroy]

  respond_to :json

  def create

    task = current_user.tasks.find(params[:sub_task][:task_id])
    if task.present?
      sub_task = task.sub_tasks.create(sub_task_params)
      respond_with sub_task, location: [task, sub_task]
    end
  end

  def update
    respond_with @sub_task.update(sub_task_params), location: [@sub_task.task , @sub_task]
  end

  def destroy
    respond_with @sub_task.destroy!
  end

  private

  def set_sub_task
    @sub_task = current_user.sub_tasks.find(params[:id])
  end

  def sub_task_params
    params.require(:sub_task).permit(:task_id, :public, :completed, :body)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!

  before_action :set_task, only: [:update, :destroy]

  
  respond_to :json

  def index
    respond_to do |format|
      format.html 
      format.json { render json: current_user.tasks.with_sub_tasks.to_json(include: :sub_tasks ) }
     end
  end

  def create
    respond_with current_user.tasks.with_sub_tasks.create(task_params)
  end

  def update
    respond_with @task.update(task_params), location: '' 
  end

  def destroy
    respond_with @task.destroy!
  end

  private

  def set_task
    @task = current_user.tasks.with_sub_tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:body, :public, :completed, :sort_order, :sub_tasks ,sub_tasks_attributes: [:id, :body,  :_destroy])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    @users = User.includes(:tasks).includes(tasks: :sub_tasks).all
  end

  def show
    @user = User.with_public_tasks.where(id: params[:id]).first
    redirect_to users_path, notice: "Sorry, this user doesn't have public tasks" unless @user.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.haml
!!!
%html{'ng-app' => 'Todo'}
  %head
    %title ToDo Rails and Angular
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body{"cz-shortcut-listen" => "true"}
    .container
      / Static navbar
      .navbar.navbar-default{role: "navigation"}
        .container-fluid
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{href: root_path} 
              ToDo App
          .navbar-collapse.collapse
            %ul.nav.navbar-nav
              %li= link_to "Home", root_path
              %li= link_to "My Tasks", tasks_path
              %li= link_to "User's List", users_path
            - if current_user
              %ul.nav.navbar-nav.navbar-right
                %li= link_to "Welcome, #{current_user.name}!", "#"
                %li= link_to "Sign out", destroy_user_session_path, data: {method: 'delete'}
            - else
              %ul.nav.navbar-nav.navbar-right
                %li= link_to "Sign In", new_user_session_path
                %li= link_to "Register", new_user_registration_path          
      - flash.each do |key, value|
        %div{:class => flash_class(key)}
          = value
      = yield
    .footer
      .container
        %p.text-muted
          This ToDo app was developed by
          =link_to "Gustavo Lazzarino", "https://bitbucket.org/gustavo_lz"

app/views/pages/home.haml
.jumbotron.grey-jumbotron
  %center
    %h1
      ToDo App
    %p
      Demo ToDo app using Ruby on Rails and Angular JS.
    - if current_user.present?
      = link_to 'My Tasks', tasks_path, class: 'btn btn-lg btn-success', role: 'button'
    -else
      = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-lg btn-success', role: 'button'

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :public %><br>
    <%= f.check_box :public %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.haml
%h1
  #{current_user.name}'s ToDo List
.task_container{'ng-controller' => 'TaskCtrl'}
  .well
    = form_tag '' ,  'ng-submit' => 'addTask()', name: 'task_form'  do |f|
      = text_field_tag :new_task, '', class: 'form-control', placeholder: 'Type a new task here and press enter', 'ng-model' => 'newTask.body', required: 'true', "maxlength" => "254"
  .bs-example
    .panel.panel-default
      / Default panel contents
      .panel-heading To be Done
      / Table
      %table.table
        %thead
          %tr
            %th Done
            %th Todo
            %th Public
            %th SubTasks
            %th Remove Task
        %tbody
          %tr{'ng-repeat' => 'task in tasks', 'ng-class' => "{'success': task.completed}"}

            %td.col-md-1
              %input{type: 'checkbox',  'ng-model' => 'task.completed', 'ng-click'=> 'toggleCompleted(task)' }
            %td.task_body.col-md-7
              %a{"editable-text" => "task.body", :href => "#", onbeforesave: "checkBody($data)", onaftersave: "saveTask(task)"} {{ task.body || "empty" }}
            %td
              %input{type: 'checkbox',  'ng-model' => 'task.public', 'ng-click'=> 'togglePublic(task)' }
            %td 
              %button.btn.btn-xs.btn-primary{ 'ng-click'=> 'editModal(task)' } ({{task.sub_tasks.length || 0}}) Manage Subtasks
            %td
              %button.btn.btn-xs.btn-danger{ 'ng-click'=> 'removeTask(task)' } Remove

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @task.body %>
</p>

<p>
  <strong>Public:</strong>
  <%= @task.public %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/users/index.haml
%h1
  All ToDos
  %small Get to know what the others are doing

%table.table.table-striped
  %thead
    %tr
      %th User
      %th Number of Tasks
      %th Number of Public Tasks
      %th Action
  %tbody
    - @users.each do |u|
      %tr
        %td= u.name
        %td= u.tasks_count
        %td= u.tasks.public_tasks.count
        %td= link_to "Check it out!", u, class: 'btn btn-primary'
        

app/views/users/show.haml
%h1
  #{@user.name}'s ToDos (#{@user.tasks.public_tasks.count})
  %small Get to know what the others are doing
.panel.panel-default
  / Default panel contents
  .panel-heading 
    %h4 Public Tasks
  / Table
  %table.table.table-striped
    %thead
      %tr
        %th.col-md-1 Last Modified
        %th.col-md-3 Todo
        %th.col-md-2 SubTasks
    %tbody
      - @user.tasks.each do |task|
        %tr
          %td= time_ago_in_words(task.updated_at) + " ago"
          %td= task.body
          %td
            %ul#selector
              - task.sub_tasks.each do |sub_task|
                %li= sub_task.body
              